---
- name: Ensure student user .ssh directory exists
  delegate_to: bastion
  become: true
  ansible.builtin.file:
    path: "~{{ ocp4_workload_bastion_student_ssh_keys_user }}/.ssh"
    state: directory
    owner: "{{ ocp4_workload_bastion_student_ssh_keys_user }}"
    group: "{{ ocp4_workload_bastion_student_ssh_keys_group }}"
    mode: u=rwx,go=

- name: Copy SSH private key to student user .ssh directory
  delegate_to: bastion
  become: true
  ansible.builtin.copy:
    src: "{{ ocp4_workload_bastion_student_ssh_keys_private_key }}"
    dest: "~{{ ocp4_workload_bastion_student_ssh_keys_user }}/.ssh/{{ ocp4_workload_bastion_student_ssh_keys_private_key | basename }}"
    owner: "{{ ocp4_workload_bastion_student_ssh_keys_user }}"
    group: "{{ ocp4_workload_bastion_student_ssh_keys_group }}"
    mode: u=rw,go=
    remote_src: true

- name: Copy SSH public key to student user .ssh directory
  delegate_to: bastion
  become: true
  ansible.builtin.copy:
    src: "{{ ocp4_workload_bastion_student_ssh_keys_public_key }}"
    dest: "~{{ ocp4_workload_bastion_student_ssh_keys_user }}/.ssh/{{ ocp4_workload_bastion_student_ssh_keys_public_key | basename }}"
    owner: "{{ ocp4_workload_bastion_student_ssh_keys_user }}"
    group: "{{ ocp4_workload_bastion_student_ssh_keys_group }}"
    mode: u=rw,go=
    remote_src: true

- name: Copy SSH config to student user .ssh directory
  delegate_to: bastion
  become: true
  ansible.builtin.copy:
    src: "{{ ocp4_workload_bastion_student_ssh_keys_ssh_config }}"
    dest: "~{{ ocp4_workload_bastion_student_ssh_keys_user }}/.ssh/config"
    owner: "{{ ocp4_workload_bastion_student_ssh_keys_user }}"
    group: "{{ ocp4_workload_bastion_student_ssh_keys_group }}"
    mode: u=rw,go=
    remote_src: true