---
- name: Create a folder in vCenter
  agnosticd.osp_on_ocp.vcenter_manage_subfolder:
    host: "{{ vcenter_hostname }}"
    login: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    folder_name: "{{ _ocp4_workload_virt_roadshow_vmware_vcenter_folder }}"
    parent_folder_name: "Workloads"
    datacenter_name: "{{ vcenter_datacenter }}"
    state: present
  register: r_vcenter_folder
  until: r_vcenter_folder is success
  retries: 10
  delay: 15

- name: Debug r_vcenter_folder
  ansible.builtin.debug:
    msg: "vcenter folder: {{ r_vcenter_folder }}"

- name: Get folder information via REST API
  ansible.builtin.uri:
    url: "https://{{ vcenter_hostname }}/api/vcenter/folder?type=VIRTUAL_MACHINE&names={{ _ocp4_workload_virt_roadshow_vmware_vcenter_folder }}"
    method: GET
    headers:
      vmware-api-session-id: "{{ _ocp4_workload_virt_roadshow_vmware_token }}"
    validate_certs: "{{ ocp4_workload_virt_roadshow_vmware_enable_cert_validation | bool }}"
    status_code: 200
  register: r_folder_info

- name: Set folder ID fact
  ansible.builtin.set_fact:
    _ocp4_workload_virt_roadshow_vmware_vcenter_folder_id: "{{ r_folder_info.json[0].folder }}"

- name: Deploy VMs from templates via REST API
  ansible.builtin.uri:
    url: "https://{{ vcenter_hostname }}/api/vcenter/vm-template/library-items/{{ (_ocp4_workload_virt_roadshow_vmware_templates | selectattr('name', 'equalto', vm.template + '-l') | first).id }}?action=deploy"
    method: POST
    headers:
      Content-Type: "application/json"
      vmware-api-session-id: "{{ _ocp4_workload_virt_roadshow_vmware_token }}"
    body_format: json
    body:
      name: "{{ vm.name }}{{ _ocp4_workload_virt_roadshow_vmware_vcenter_vmname_suffix }}"
      placement:
        cluster: "{{ _ocp4_workload_virt_roadshow_vmware_vcenter_cluster_id }}"
        folder: "{{ _ocp4_workload_virt_roadshow_vmware_vcenter_folder_id }}"
      disk_storage:
        datastore: "{{ _ocp4_workload_virt_roadshow_vmware_datastore_id }}"
      powered_on: false
    validate_certs: "{{ ocp4_workload_virt_roadshow_vmware_enable_cert_validation | bool }}"
    status_code:
      - 200
      - 400
  retries: 5
  delay: 10
  until: r_vmc_instance is success
  failed_when:
    - r_vmc_instance.status == 400
    - r_vmc_instance.json.error_type | default('') != 'ALREADY_EXISTS'
  loop: "{{ ocp4_workload_virt_roadshow_vmware_vms }}"
  loop_control:
    loop_var: vm
    label: "{{ vm.name }}"
  register: r_vmc_instance
