---
- name: Get vCenter SHA1 fingerprint
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail &&
      openssl s_client
      -connect {{ vcenter_hostname }}:443
      < /dev/null 2>/dev/null
      | openssl x509 -fingerprint -noout -in /dev/stdin
      | cut -d '=' -f 2
  register: r_sha1

- name: Set SHA1 fact
  ansible.builtin.set_fact:
    _ocp4_workload_virt_roadshow_vmware_vcenter_sha1: "{{ r_sha1.stdout }}"

- name: Print SHA1
  ansible.builtin.debug:
    msg: "vCenter SHA1: {{ _ocp4_workload_virt_roadshow_vmware_vcenter_sha1 }}"

- name: Set up MTV VMware credentials secret
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'secret_vmware_credentials.yaml.j2') }}"

- name: Set up MTV VMware provider
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'forklift_provider_vmware.yaml.j2') }}"
